controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mobile_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50.0
    odom_frame_id: odom
    enable_odom_tf: false # false due to jitter
    base_frame_id: base_footprint
    open_loop: false
    pose_covariance_diagonal: [0.0025, 0.0025, 1e6, 1e6, 1e6, 0.04]
    twist_covariance_diagonal: [0.01, 0.01, 1e6, 1e6, 1e6, 0.05]

    left_wheel_names: ["base_to_left_wheel"]
    right_wheel_names: ["base_to_right_wheel"]

    wheel_separation: 0.452 # m
    wheel_radius: 0.049 # m (9.8 cm dia)
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.25

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.30 # m/s (~60 RPM wheel speed)
        min_velocity: -0.30
        has_acceleration_limits: true
        max_acceleration: 0.25 # smooth ramp-up
        min_acceleration: -0.25
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.10 # rad/s (~60Â°/s)
        has_acceleration_limits: true
        max_acceleration: 0.60
        has_jerk_limits: false
